### ISSUE TITLE
No registered env with id: JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0

### ISSUE THREAD

**Issue by nico1as** [Gor-Ren/gym-jsbsim#1]
Hello, 

Thanks for sharing your code.
I'm in trouble trying to set one of your JSBSim Id environement. The id is not recognised: 

```
Traceback (most recent call last):
  File "/home/nico/anaconda3/envs/py36/lib/python3.6/site-packages/gym/envs/registration.py", line 143, in spec
    return self.env_specs[id]
KeyError: 'JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    env = gym.make('JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0')
  File "/home/nico/anaconda3/envs/py36/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/nico/anaconda3/envs/py36/lib/python3.6/site-packages/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/home/nico/anaconda3/envs/py36/lib/python3.6/site-packages/gym/envs/registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0
```
Do you have any idea ?

Many thanks, 

Nicolas

**Comment by bertram1isu** [comment]
You can dump out all of the environment strings with something like:

```
import gym
import jsbsim
import gym_jsbsim

for env in gym.envs.registry.all():
    # Debug:  Print out all the gym_jsbsim environments because they're
    # very tricky to get the string correct.
    print( 'env: %s' % env.id )
```

I think that SHAPING should not be all caps (the README.md is wrong).. and should instead be Shaping.  I think also the TurnHeadingControl needs to be named TurnHeadingControlTask.

Here's what I'm using:

JSBSim-TurnHeadingControlTask-Cessna172P-Shaping.STANDARD-NoFG-v0

**Comment by nico1as** [comment]
Thanks very much, it is working

**Comment by Gor-Ren** [comment]
Updated the readme with correct environment ID; sorry about that.
